version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: online_diary_development
      POSTGRES_USER: nitail
      POSTGRES_PASSWORD: frustraciya
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: nitail
      DATABASE_PASSWORD: frustraciya
      DATABASE_NAME: online_diary_development
      DATABASE_PORT: 5432
      RAILS_ENV: development

volumes:
  postgres_data:
